FROM python:3.7-alpine
RUN apk add libxml2-dev libxslt-dev gcc musl-dev && mkdir /app

COPY ./requirements.txt /app

WORKDIR /app
RUN pip install -r requirements.txt
COPY . /app
ENTRYPOINT ["python"]
CMD ["app.py"]
